apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: my-flask-app
        image: gcr.io/proyecto-retodevops/my-flask-app:v1
        ports:
        - containerPort: 5000
        env:
        - name: API_KEY
          value: "2f5ae96c-b558-4c7b-a590-a501ae1c3f6c"
